### ISSUE TITLE
copy user roles returning 0 results on search

### ISSUE THREAD

**Issue by MalcolmAnders** [HSG-Library/alma-copy-user-roles#17] opened 2022-07-18 12:02 UTC
Dear Jonas,

I have recently activated copy user roles on our Alma implementation but have encountered some behaviour which I'm confused by- upon searching for a user to copy to the target user, I and other colleagues (that have the required roles to use the app) keep getting 0 results for user profiles which do exist. There are no error codes delivered as a result of this search either:

![0 user results](https://user-images.githubusercontent.com/94921304/179506663-aa051031-071b-437e-8b6f-b56857a8c634.jpg)

Apologies for taking up your time with this, but do you have any advice about how I might go about fixing this issue? Happy to provide more info about our implementation if you need it.

Thank you,

Malcolm Anderson

**Comment by d22** [comment] 2022-07-19 09:25
Hi @MalcolmAnders 

This is indeed strange. A few questions/things you can try:

- Do you get any results if you search for a very short term like 'as'?
- Try a 'primary id' instead of a 'name' as search term

When you open your browsers Developer Tools:
- Are there any errors or warnings in the browsers console?
- In the network tab, after searching, do you see the search request, which should look something like this: `https://<your-alma-host>/almaws/v1/users?q=ALL~*jonas*&order_by=last_name,first_name,primary_id&limit=30&_=1658222209651`

I hope we can find a solution to this issue.
Br
Jonas

**Comment by MalcolmAnders** [comment] 2022-07-19 15:47
Hello Jonas,

Thank you for your advice- searching for the primary identifier worked as intended so that makes the app usable for us, and also performing shorter searches of a few characters or a first name only did give results, but searching a first and surname still yield 0.

Checking the console and network with inspector didn't show any errors in console and the search request was displaying in the network tab with a 200 'ok' indicator.

As mentioned the primary id means we can use the app fine, but let me know if I can help any more if you're investigating any search inconsistencies, and thank you again for your help.

Best wishes,

Malcolm

**Comment by d22** [comment] 2022-07-20 06:37
Hi @MalcolmAnders 

I'm glad it's working for you now. 
Unfortunately I can't reproduce the behavior in our environment, but I would like to understand where the problem is.

Can you tell me what the request looks like that is made? My expectation would be something like this:

    https://<your-inst>.alma.exlibrisgroup.com/almaws/v1/users?q=ALL~*john_doe*&order_by=last_name,first_name,primary_id&limit=30&_=1658298871673

Thanks for your help, 
Jonas

**Comment by d22** [comment] 2022-08-09 09:07
Since this seems to be resolved, I will close this issue. 
If this problem persists, please open a new issue.

**Closed as completed by d22** 2022-08-09 09:07 UTC
